<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CastJournal.Common\CastJournal.Common.csproj" />
    <ProjectReference Include="..\CastJournal.Domain\CastJournal.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Locations\" />
    <Folder Include="DTOs\Auth\" />
    <Folder Include="DTOs\Media\" />
    <Folder Include="DTOs\Species\" />
    <Folder Include="Features\" />
    <Folder Include="Common\" />
    <Folder Include="Validators\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
